import type { Brand } from "./brand";

/** Server-generated by `initiate-upload`. The client can never supply one. */
export type ClipId = Brand<string, "ClipId">;

/** Equal to `ClipId` server-side, but kept distinct so the equality is asserted in a mapper, not assumed at call sites. */
export type JobId = Brand<string, "JobId">;

export type SessionId = Brand<string, "SessionId">;
export type UserId = Brand<string, "UserId">;
export type TrickId = Brand<string, "TrickId">;

/** Client-supplied attempt identifier (<= 80 chars), accepted by the sync endpoint. */
export type AttemptId = Brand<string, "AttemptId">;

/** Client-owned identifier that exists before the first network call (guardrails 7). */
export type LocalId = Brand<string, "LocalId">;
